kubectl apply -f namespace.yaml
kubectl apply -f configmap.yaml
kubectl apply -f secret.yaml
kubectl apply -f app-deployment.yaml
kubectl apply -f redis-deployment.yaml
kubectl apply -f db1-deployment.yaml
kubectl apply -f db2-deployment.yaml
kubectl apply -f prometheus-deployment.yaml
kubectl apply -f loki-deployment.yaml
kubectl apply -f promtail-deployment.yaml
kubectl apply -f services.yaml
