# app-deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: app
  namespace: ecommerce
spec:
  replicas: 2
  selector:
    matchLabels:
      app: app
  template:
    metadata:
      labels:
        app: app
    spec:
      containers:
      - name: app
        image: your-docker-image
        ports:
        - containerPort: 8080
        env:
        - name: REDIS_ADDRESS
          value: "redis:6379"
        - name: MYSQL_HOST_1
          value: "db1"
        - name: MYSQL_HOST_2
          value: "db2"
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: db-secret
              key: mysql-root-password
        volumeMounts:
        - name: log-volume
          mountPath: /path/to/your/logfile.log
          subPath: logfile.log
      volumes:
      - name: log-volume
        emptyDir: {}

