# services.yaml
apiVersion: v1
kind: Service
metadata:
  name: app
  namespace: ecommerce
spec:
  selector:
    app: app
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080

---

apiVersion: v1
kind: Service
metadata:
  name: redis
  namespace: ecommerce
spec:
  selector:
    app: redis
  ports:
    - protocol: TCP
      port: 6379
      targetPort: 6379

---

apiVersion: v1
kind: Service
metadata:
  name: db1
  namespace: ecommerce
spec:
  selector:
    app: db1
  ports:
    - protocol: TCP
      port: 3306
      targetPort: 3306

---

apiVersion: v1
kind: Service
metadata:
  name: db2
  namespace: ecommerce
spec:
  selector:
    app: db2
  ports:
    - protocol: TCP
      port: 3307
      targetPort: 3307

---

apiVersion: v1
kind: Service
metadata:
  name: prometheus
  namespace: ecommerce
spec:
  selector:
    app: prometheus
  ports:
    - protocol: TCP
      port: 9090
      targetPort: 9090

---

apiVersion: v1
kind: Service
metadata:
  name: loki
  namespace: ecommerce
spec:
  selector:
    app: loki
  ports:
    - protocol: TCP
      port: 3100
      targetPort: 3100

---

apiVersion: v1
kind: Service
metadata:
  name: promtail
  namespace: ecommerce
spec:
  selector:
    app: promtail
  ports:
    - protocol: TCP
      port: 9080
      targetPort: 9080
